services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tax_db
    ports:
      - "5432:5432"

  compute:
    build:
      context: .
      dockerfile: services/compute/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tax_db
    depends_on:
      - db
    ports:
      - "8080:8080"

  ingest:
    build:
      context: .
      dockerfile: services/ingest/Dockerfile
    depends_on:
      - compute
    ports:
      - "3000:3000"

  loadtest:
    build:
      context: .
      dockerfile: services/loadtest/Dockerfile
    environment:
      - COMPUTE_URL=http://compute:8080/api/compute
      - CONCURRENCY=10
      - REQUESTS_PER_TASK=100
    depends_on:
      - compute
